apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-workflows
helmCharts:
  - name: argo-workflows
    repo: https://argoproj.github.io/argo-helm
    includeCRDs: true
    releaseName: argo-workflows
    version: 0.40.1
    additionalValuesFiles:
    - values.yaml
    - ha-values.yaml
resources: 
  - namespace.yaml
